{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "image-preloader.serviceAccountName" . }}
  labels:
    {{- include "image-preloader.labels" . | nindent 4 }}
{{- end }}
